version: '3'

services:
  master1:
    image: elasticsearch:7.7.0
    environment:
      - node.name=master1
      - node.master=true
      - network.host=0.0.0.0
      - discovery.type=zen
      - discovery.seed_hosts=master1,master2,master3
      - cluster.initial_master_nodes=master1,master2,master3
      - cluster.name=valorant_cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - master1_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
  master2:
    image: elasticsearch:7.7.0
    environment:
      - node.name=master2
      - node.master=true
      - network.host=0.0.0.0
      - discovery.type=zen
      - discovery.seed_hosts=master1,master2,master3
      - cluster.initial_master_nodes=master1,master2,master3
      - cluster.name=valorant_cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - master2_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
  master3:
    image: elasticsearch:7.7.0
    environment:
      - node.name=master3
      - node.master=true
      - network.host=0.0.0.0
      - discovery.type=zen
      - discovery.seed_hosts=master1,master2,master3
      - cluster.initial_master_nodes=master1,master2,master3
      - cluster.name=valorant_cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - master3_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  master1_data:
  master2_data:
  master3_data:
